name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Silleellie/pylint-github-action@v2
      with: 
        lint-path: |
          components
          config
          services
          util
          main.py
        python-version: 3.10.12
        badge-text: Pylint
