[theme]
primaryColor = "#FF6500"      # Biru pastel
backgroundColor = "#0B192C"   # Putih bersih untuk latar belakang
secondaryBackgroundColor = "#1E3E62" # Abu-abu muda untuk area sekunder
textColor = "#FBFBFB"         # Abu-abu gelap untuk teks
font = "sans serif"           # Font modern yang mudah dibaca
